name: reserva_pista
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  equatable: ^2.0.5
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  # State management
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/